[package]
name = "lis"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
clap = { version = "4.5.13", features = ["derive"] }
ctrlc = "3.4.5"
env_logger = "0.11.5"
fuser = "0.14.0"
futures-lite = "2.3.0"
iroh = "0.23.0"
libc = "0.2.158"
log = "0.4.22"
serde = "1.0.205"
serde_json = "1.0.122"
tempfile = "3.12.0"
tokio = "1.39.2"
